# Generated by Django 3.0.1 on 2020-01-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_name', models.CharField(db_index=True, max_length=32, verbose_name='姓名')),
                ('position', models.CharField(max_length=32, verbose_name='职位')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '主要人员',
                'verbose_name_plural': '主要人员',
            },
        ),
    ]
