# Generated by Django 3.0.1 on 2020-01-03 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniform_social_credit_code', models.CharField(max_length=18, verbose_name='统一社会信用代码')),
                ('name', models.CharField(max_length=128, verbose_name='企业名称')),
                ('registered_capital', models.IntegerField(db_index=True, null=True, verbose_name='注册资本')),
                ('paid_up_capital', models.IntegerField(null=True, verbose_name='实缴资本')),
                ('business_scope', models.CharField(max_length=1024, null=True, verbose_name='经营范围')),
                ('industry', models.CharField(db_index=True, max_length=128, null=True, verbose_name='所属行业')),
                ('tel', models.CharField(max_length=64, null=True, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('province', models.CharField(db_index=True, max_length=32, null=True, verbose_name='省')),
                ('city', models.CharField(max_length=32, null=True, verbose_name='市')),
                ('district', models.CharField(max_length=32, null=True, verbose_name='县/区')),
                ('detail_address', models.CharField(max_length=128, null=True, verbose_name='详细地址')),
                ('company_type', models.CharField(max_length=128, null=True, verbose_name='企业类型')),
                ('business_registration_number', models.CharField(max_length=14, null=True, verbose_name='工商注册号')),
                ('registration_authority', models.CharField(max_length=128, null=True, verbose_name='登记机关')),
                ('operating_status', models.CharField(max_length=64, null=True, verbose_name='经营范围')),
            ],
            options={
                'verbose_name': '企业基础信息',
                'verbose_name_plural': '企业基础信息',
            },
        ),
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('image_url', models.URLField(verbose_name='商标')),
                ('name', models.CharField(max_length=128, verbose_name='商标名称')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '商标注册',
                'verbose_name_plural': '商标注册',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=64, verbose_name='国际分类')),
                ('process', models.CharField(max_length=64, verbose_name='商标流程')),
                ('status', models.CharField(max_length=16, verbose_name='商标状态')),
                ('trademark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Trademark', verbose_name='商标名称')),
            ],
            options={
                'verbose_name': '商标分类信息',
                'verbose_name_plural': '商标分类信息',
            },
        ),
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateField(verbose_name='变更时间')),
                ('change_item', models.CharField(max_length=256, verbose_name='变更项目')),
                ('before_change', models.CharField(max_length=1024, verbose_name='变更前')),
                ('after_change', models.CharField(max_length=1024, verbose_name='变更后')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='所属企业')),
            ],
            options={
                'verbose_name': '企业变更信息',
                'verbose_name_plural': '企业变更信息',
            },
        ),
    ]
